# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:50
from __future__ import unicode_literals

import apps.producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20171213_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(height_field=200, upload_to=apps.producto.models.user_directory_path, width_field=200),
        ),
    ]
