# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('producto', '0005_auto_20171215_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad', models.SmallIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(choices=[('B', 'Boleta'), ('F', 'Factura'), ('T', 'Ticket')], default='B', max_length=1)),
                ('serie', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=4)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pago', models.DecimalField(decimal_places=2, max_digits=14)),
                ('detalleventas', models.ManyToManyField(through='venta.DetalleVenta', to='producto.Producto')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.Venta'),
        ),
    ]
