# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='permisos',
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inicio.Menu'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.ManyToManyField(through='inicio.Permiso', to='inicio.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
