# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('materno', models.CharField(max_length=50)),
                ('paterno', models.CharField(max_length=50)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(max_length=2)),
                ('cod_pro', models.CharField(max_length=2)),
                ('cod_dis', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='ubigeo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.Ubigeo'),
        ),
    ]
